apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2
  template:
    metadata:
      labels:
        app: container-2
    spec:
      containers:
      - name: container-2
        image:  us-central1-docker.pkg.dev/csci5409cloudcomputing-453821/container-repository/container2:latest
        volumeMounts:
        - mountPath: /samruddhi_PV_dir  
          name: standard-volume
      volumes:
      - name: standard-volume
        persistentVolumeClaim:
          claimName: samruddhi-pvc 
