apiVersion: v1
kind: Service
metadata:
  name: container-2-service
spec:
  selector:
    app: container-2  
  ports:
    - protocol: TCP
      port: 6001  
      targetPort: 6001 
  type: ClusterIP  
